### ISSUE TITLE
На андройде не показывает

### ISSUE THREAD

**Issue by 041RDK003** [sa1nt/track.js#1]
Сервак поднял, 
вылез на него с мобилы, 
ввёл имя 
+ на компе зашёл
OBSERVED:
точка копа есть (на компе) а на мобиле нету.. и мобилы нету..

**Comment by 041RDK003** [comment]
UPD: Mobile Chrome is not supported
All ok for FF

**Comment by sa1nt** [comment]
Please ensure that you visit the page using https.
