### ISSUE TITLE
Investigate if device going to sleep is a problem

### ISSUE THREAD

**Issue by sa1nt** [sa1nt/track.js#2]
If yes - use something like NoSleep.js to prevent sleep.

There should also probably be a switch to turn this no-sleep on/off.

**Comment by 041RDK003** [comment]
no-sleep on/off - great idea

**Comment by sa1nt** [comment]
Investigated this, and the only usable thing found was [NoSleep.js](https://github.com/richtr/NoSleep.js/). It works by creating an invisible video inside the page and looping it endlessly. While this does achieve the goal, my laptop's battery got drained in an hour of this being on. 

So, won't fix.
